name: BackEnd - Micros - K8s
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Which env?
        options:
        - qa
        - main
      build-api:
        type: boolean
        description: api-service
      build-event:
        type: boolean
        description: event-service
      build-user:
        type: boolean
        description: user-service
      build-inventory:
        type: boolean
        description: inventory-service

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  BRANCH_NAME: ${{github.event.inputs.env}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: source
        submodules: recursive
        fetch-depth: 0

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Cloning Management Core and switching to ${{ env.BRANCH_NAME }}
      working-directory: source
      run: |
        cd ..
        git clone git@github.com:AR-DL/management_core.git
        cd management_core
        git checkout ${{ env.BRANCH_NAME }}
        cd ../source

    - name: Cloning Management Api and switching to ${{ env.BRANCH_NAME }}
      if: ${{github.event.inputs.build-api == 'true' }}
      working-directory: source
      run: |
        cd ..
        git clone git@github.com:AR-DL/management_api.git
        cd management_api
        git checkout ${{ env.BRANCH_NAME }}

    - name: Build core
      working-directory: source
      run: |
        cd ../management_core
        mvn clean install

    - name: Build
      working-directory: source
      run: |
        cd ../management_api/api_service
        mvn package
